/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication7;

import java.awt.Color;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author CHIRAG VOHRA
 */
public class EditCourse extends javax.swing.JFrame {

    /**
     * Creates new form EditCourse
     */
    public EditCourse() {
        initComponents();
        setRecordstoTable();
    }
    DefaultTableModel model;
    public void setRecordstoTable(){
            try{
               Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/fees_mange_sys","root","Chirag@123");
            PreparedStatement pst = con.prepareStatement("select * from coursedb");
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                String courseid = rs.getString("id");
               
                String courseName=rs.getString("coursename");
                String cost = rs.getString("coursecost");
                
                Object[] obj = {courseid,courseName,cost};
               model = (DefaultTableModel)tbl_courses.getModel();
               model.addRow(obj);
            }
            }catch(Exception e){
                e.printStackTrace();
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsidebar = new javax.swing.JPanel();
        viewrecordpanel = new javax.swing.JPanel();
        homelabel = new javax.swing.JLabel();
        searchpanel = new javax.swing.JPanel();
        homelabel1 = new javax.swing.JLabel();
        editcoursepanel = new javax.swing.JPanel();
        homelabel2 = new javax.swing.JLabel();
        homepanel = new javax.swing.JPanel();
        homelabel3 = new javax.swing.JLabel();
        backpanel = new javax.swing.JPanel();
        homelabel4 = new javax.swing.JLabel();
        logoutpanel = new javax.swing.JPanel();
        homelabel5 = new javax.swing.JLabel();
        contactpanel = new javax.swing.JPanel();
        homelabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_courses = new javax.swing.JTable();
        txt_cname = new javax.swing.JTextField();
        txt_cid = new javax.swing.JTextField();
        txt_ccost = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsidebar.setBackground(new java.awt.Color(51, 0, 153));
        panelsidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewrecordpanel.setBackground(new java.awt.Color(51, 0, 153));
        viewrecordpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        viewrecordpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewrecordpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewrecordpanelMouseExited(evt);
            }
        });
        viewrecordpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel.setForeground(new java.awt.Color(255, 255, 255));
        homelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/view all record.png"))); // NOI18N
        homelabel.setText("View Records");
        viewrecordpanel.add(homelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 280, 70));

        panelsidebar.add(viewrecordpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 330, 70));

        searchpanel.setBackground(new java.awt.Color(51, 0, 153));
        searchpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        searchpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchpanelMouseExited(evt);
            }
        });
        searchpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel1.setForeground(new java.awt.Color(255, 255, 255));
        homelabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/search2.png"))); // NOI18N
        homelabel1.setText("Search Record");
        homelabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homelabel1MouseClicked(evt);
            }
        });
        searchpanel.add(homelabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, -1));

        panelsidebar.add(searchpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 330, 70));

        editcoursepanel.setBackground(new java.awt.Color(51, 0, 153));
        editcoursepanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        editcoursepanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editcoursepanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editcoursepanelMouseExited(evt);
            }
        });
        editcoursepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel2.setForeground(new java.awt.Color(255, 255, 255));
        homelabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/edit2.png"))); // NOI18N
        homelabel2.setText("Edit Courses");
        homelabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homelabel2MouseClicked(evt);
            }
        });
        editcoursepanel.add(homelabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 60));

        panelsidebar.add(editcoursepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 330, 70));

        homepanel.setBackground(new java.awt.Color(51, 0, 153));
        homepanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        homepanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homepanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homepanelMouseExited(evt);
            }
        });
        homepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel3.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel3.setForeground(new java.awt.Color(255, 255, 255));
        homelabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/home.png"))); // NOI18N
        homelabel3.setText("  Home");
        homelabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homelabel3MouseClicked(evt);
            }
        });
        homepanel.add(homelabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 50));

        panelsidebar.add(homepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 330, 70));

        backpanel.setBackground(new java.awt.Color(51, 0, 153));
        backpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        backpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backpanelMouseExited(evt);
            }
        });
        backpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel4.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel4.setForeground(new java.awt.Color(255, 255, 255));
        homelabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/back-button.png"))); // NOI18N
        homelabel4.setText("Back");
        homelabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homelabel4MouseClicked(evt);
            }
        });
        backpanel.add(homelabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 70));

        panelsidebar.add(backpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 330, 70));

        logoutpanel.setBackground(new java.awt.Color(51, 0, 153));
        logoutpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        logoutpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutpanelMouseExited(evt);
            }
        });
        logoutpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel5.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel5.setForeground(new java.awt.Color(255, 255, 255));
        homelabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/logout.png"))); // NOI18N
        homelabel5.setText("Logout");
        homelabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homelabel5MouseClicked(evt);
            }
        });
        logoutpanel.add(homelabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 70));

        panelsidebar.add(logoutpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 330, 70));

        contactpanel.setBackground(new java.awt.Color(51, 0, 153));
        contactpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        contactpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contactpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactpanelMouseExited(evt);
            }
        });
        contactpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel6.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel6.setForeground(new java.awt.Color(255, 255, 255));
        homelabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/admin.png"))); // NOI18N
        homelabel6.setText("Contact Us");
        contactpanel.add(homelabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 250, 70));

        panelsidebar.add(contactpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 330, 70));

        jLabel16.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 0, 153));
        jLabel16.setText("Remarks : ");
        panelsidebar.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 670, -1, 40));

        getContentPane().add(panelsidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, 380, 1040));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_courses.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        tbl_courses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID", "Course Name", "Course Cost"
            }
        ));
        tbl_courses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_coursesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_courses);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 124, 661, 463));

        txt_cname.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        txt_cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cnameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 227, 40));

        txt_cid.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        txt_cid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cidActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 200, 227, 40));

        txt_ccost.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        txt_ccost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ccostActionPerformed(evt);
            }
        });
        jPanel1.add(txt_ccost, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 227, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("Course Cost :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 151, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setText("Course ID :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 151, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setText("Course Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 151, 40));

        jButton1.setBackground(new java.awt.Color(51, 0, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/add2.png"))); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 40));

        jButton2.setBackground(new java.awt.Color(51, 0, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/update.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));

        jButton3.setBackground(new java.awt.Color(51, 0, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/delete.png"))); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 131, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 1050));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void viewrecordpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewrecordpanelMouseEntered
        Color clr = new Color(48,0,178);
        viewrecordpanel.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_viewrecordpanelMouseEntered

    private void viewrecordpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewrecordpanelMouseExited
        Color clr = new Color(51,0,153);
        viewrecordpanel.setBackground(clr);
    }//GEN-LAST:event_viewrecordpanelMouseExited

    private void searchpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchpanelMouseEntered
        Color clr = new Color(48,0,178);
        searchpanel.setBackground(clr);
    }//GEN-LAST:event_searchpanelMouseEntered

    private void searchpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchpanelMouseExited
        Color clr = new Color(51,0,153);
        searchpanel.setBackground(clr);
    }//GEN-LAST:event_searchpanelMouseExited

    private void editcoursepanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editcoursepanelMouseEntered
        Color clr = new Color(48,0,178);
        editcoursepanel.setBackground(clr);
    }//GEN-LAST:event_editcoursepanelMouseEntered

    private void editcoursepanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editcoursepanelMouseExited
        Color clr = new Color(51,0,153);
        editcoursepanel.setBackground(clr);
    }//GEN-LAST:event_editcoursepanelMouseExited

    private void homepanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepanelMouseEntered
        Color clr = new Color(48,0,178);
        homepanel.setBackground(clr);
    }//GEN-LAST:event_homepanelMouseEntered

    private void homepanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepanelMouseExited
        Color clr = new Color(51,0,153);
        homepanel.setBackground(clr);
    }//GEN-LAST:event_homepanelMouseExited

    private void backpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backpanelMouseEntered
        Color clr = new Color(48,0,178);
        backpanel.setBackground(clr);
    }//GEN-LAST:event_backpanelMouseEntered

    private void backpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backpanelMouseExited
        Color clr = new Color(51,0,153);
        backpanel.setBackground(clr);
    }//GEN-LAST:event_backpanelMouseExited

    private void homelabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelabel5MouseClicked
        LoginPage lp = new LoginPage();
       lp.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_homelabel5MouseClicked

    private void logoutpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutpanelMouseClicked
        SignuUpPage signup = new SignuUpPage();
        signup.show();
        this.dispose();
    }//GEN-LAST:event_logoutpanelMouseClicked

    private void logoutpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutpanelMouseEntered
        Color clr = new Color(48,0,178);
        logoutpanel.setBackground(clr);
    }//GEN-LAST:event_logoutpanelMouseEntered

    private void logoutpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutpanelMouseExited
        Color clr = new Color(51,0,153);
        logoutpanel.setBackground(clr);
    }//GEN-LAST:event_logoutpanelMouseExited

    private void contactpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanelMouseClicked
        ContactUs contact = new ContactUs();
        contact.show();
    }//GEN-LAST:event_contactpanelMouseClicked

    private void contactpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanelMouseEntered
        Color clr = new Color(48,0,178);
        contactpanel.setBackground(clr);
    }//GEN-LAST:event_contactpanelMouseEntered

    private void contactpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanelMouseExited
        Color clr = new Color(51,0,153);
        contactpanel.setBackground(clr);
    }//GEN-LAST:event_contactpanelMouseExited

    private void txt_cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cnameActionPerformed

    private void txt_cidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cidActionPerformed

    private void txt_ccostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ccostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ccostActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     int id = Integer.parseInt(txt_cid.getText());
     String cname = txt_cname.getText();
    double cost = Double.parseDouble(txt_ccost.getText());
    addCourse(id,cname,cost);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int id = Integer.parseInt(txt_cid.getText());
     String cname = txt_cname.getText();
    double cost = Double.parseDouble(txt_ccost.getText());
    updateCourse(id,cname,cost);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       int id = Integer.parseInt(txt_cid.getText());
     String cname = txt_cname.getText();
    double cost = Double.parseDouble(txt_ccost.getText());
   deleteCourse(id,cname,cost);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tbl_coursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_coursesMouseClicked
    int rowno=    tbl_courses.getSelectedRow();
    TableModel model = tbl_courses.getModel();
    txt_cid.setText(model.getValueAt(rowno, 0).toString());
     txt_cname.setText(model.getValueAt(rowno, 0).toString());
     txt_ccost.setText(model.getValueAt(rowno, 2).toString());
    }//GEN-LAST:event_tbl_coursesMouseClicked

    private void homelabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelabel3MouseClicked
 HomePage hm =new HomePage();
       hm.setVisible(true);
       this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_homelabel3MouseClicked

    private void homelabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelabel1MouseClicked
 SearchRecords sr = new SearchRecords();
      sr.setVisible(true);
      this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_homelabel1MouseClicked

    private void homelabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelabel4MouseClicked
 HomePage hm =new HomePage();
       hm.setVisible(true);
       this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_homelabel4MouseClicked

    private void homelabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelabel2MouseClicked
EditCourse ec = new   EditCourse();
ec.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_homelabel2MouseClicked
       
    public void clearData(){
            model = (DefaultTableModel)tbl_courses.getModel();
            model.setRowCount(0);
    }
    public void addCourse(int id,String cname,double cost) 
    {
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/fees_mange_sys","root","Chirag@123");
            PreparedStatement pst = con.prepareStatement("insert into coursedb values(?,?,?)");
        pst.setInt(1, id);
        pst.setString(2, cname);
        pst.setDouble(3, cost);
        int i = pst.executeUpdate();
        if(i>0){
            JOptionPane.showMessageDialog(this, "Course added successfully");
            clearData();
            setRecordstoTable();
        }
        else{
             JOptionPane.showMessageDialog(this, "Failed");
        }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    public void updateCourse(int id,String cname,double cost) 
    {
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/fees_mange_sys","root","Chirag@123");
            PreparedStatement pst = con.prepareStatement("update coursedb set coursename=?,coursecost=? where id=?");
       
        pst.setString(1, cname);
        pst.setDouble(2, cost);
         pst.setInt(3, id);
        int i = pst.executeUpdate();
        if(i>0){
            JOptionPane.showMessageDialog(this, "Course Updated successfully");
            clearData();
            setRecordstoTable();
        }
        else{
             JOptionPane.showMessageDialog(this, "Failed");
        }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    public void deleteCourse(int id,String cname,double cost) 
    {
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/fees_mange_sys","root","Chirag@123");
            PreparedStatement pst = con.prepareStatement("delete from coursedb where id=?");
       
//        pst.setString(1, cname);
//        pst.setDouble(2, cost);
         pst.setInt(1, id);
        int i = pst.executeUpdate();
        if(i>0){
            JOptionPane.showMessageDialog(this, "Course deletion successfully");
            clearData();
            setRecordstoTable();
        }
        else{
             JOptionPane.showMessageDialog(this, "Failed");
        }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backpanel;
    private javax.swing.JPanel contactpanel;
    private javax.swing.JPanel editcoursepanel;
    private javax.swing.JLabel homelabel;
    private javax.swing.JLabel homelabel1;
    private javax.swing.JLabel homelabel2;
    private javax.swing.JLabel homelabel3;
    private javax.swing.JLabel homelabel4;
    private javax.swing.JLabel homelabel5;
    private javax.swing.JLabel homelabel6;
    private javax.swing.JPanel homepanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel logoutpanel;
    private javax.swing.JPanel panelsidebar;
    private javax.swing.JPanel searchpanel;
    private javax.swing.JTable tbl_courses;
    private javax.swing.JTextField txt_ccost;
    private javax.swing.JTextField txt_cid;
    private javax.swing.JTextField txt_cname;
    private javax.swing.JPanel viewrecordpanel;
    // End of variables declaration//GEN-END:variables
}
