/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication7;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;

/**
 *
 * @author CHIRAG VOHRA
 */
public class PrintReceipt extends javax.swing.JFrame {

    /**
     * Creates new form PrintReceipt
     */
    public PrintReceipt() {
        initComponents();
        getRecords();
    }
    
    
    public void getRecords(){
         try {
            // TODO code application logic here
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/fees_mange_sys","root","Chirag@123");
            
            PreparedStatement stmt = con.prepareStatement("select * from feess order by receiptno desc limit 1");
            ResultSet rs = stmt.executeQuery();
            rs.next();
            txt_receiptno.setText(rs.getString("receiptno"));
            txt_received.setText(rs.getString("studentnaam"));
            txt_roll.setText(rs.getString("rolllnoo"));
            txt_date.setText(rs.getString("dateoffees"));
            txt_initialamount1.setText(rs.getString("initialMoney"));
            txt_totalamount.setText(rs.getString("totalMoney"));
            txt_totalinwords.setText(rs.getString("moneyInWords"));
            txt_paymentmode.setText(rs.getString("paymentMode"));
            txt_bankname.setText(rs.getString("bankName"));
            txt_gst1.setText(rs.getString("gstnoo"));
            txt_cgst.setText(rs.getString("cgstt"));
             txt_sgst.setText(rs.getString("sgstt"));
             txt_coursenaam.setText(rs.getString("coursenaam"));
             txt_remarks.setText(rs.getString("remarkss"));
             txt_year1.setText(rs.getString("year11"));
             txt_year2.setText(rs.getString("year22"));
            
             String payementmode = rs.getString("paymentMode");
             if(payementmode.equalsIgnoreCase("UPI/Cash")){
                 lbl_cheque.setText("Cheque No.");
                txt_cheque.setText("");
//                lbl_bankname.setText("Bank name");
                txt_bankname.setText("-");
             }
             if(payementmode.equalsIgnoreCase("cheque")){
                 lbl_cheque.setText("Cheque No.");
                txt_cheque.setText(rs.getString("chequenoo"));
//                lbl_bankname.setText("Bank name");
                txt_bankname.setText(rs.getString("bankName"));
             }
              if(payementmode.equalsIgnoreCase("DD")){
                 lbl_cheque.setText("DD No.");
                txt_cheque.setText(rs.getString("ddnoo"));
//                lbl_bankname.setText("Bank name");
                txt_bankname.setText(rs.getString("bankName"));
             }
               if(payementmode.equalsIgnoreCase("Debit/Credit card")){
                 lbl_cheque.setText("");
                txt_cheque.setText("");
//                lbl_bankname.setText("Bank name");
                txt_bankname.setText(rs.getString("bankName"));
             }
            
    }   
         catch(Exception e){
             e.printStackTrace();
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsidebar = new javax.swing.JPanel();
        viewrecordpanel = new javax.swing.JPanel();
        homelabel = new javax.swing.JLabel();
        searchpanel = new javax.swing.JPanel();
        homelabel1 = new javax.swing.JLabel();
        editcoursepanel = new javax.swing.JPanel();
        homelabel2 = new javax.swing.JLabel();
        homepanel = new javax.swing.JPanel();
        homelabel3 = new javax.swing.JLabel();
        backpanel = new javax.swing.JPanel();
        homelabel4 = new javax.swing.JLabel();
        logoutpanel = new javax.swing.JPanel();
        homelabel5 = new javax.swing.JLabel();
        contactpanel = new javax.swing.JPanel();
        homelabel6 = new javax.swing.JLabel();
        contactpanel1 = new javax.swing.JPanel();
        homelabel7 = new javax.swing.JLabel();
        contactpanel4 = new javax.swing.JPanel();
        homelabel10 = new javax.swing.JLabel();
        contactpanel5 = new javax.swing.JPanel();
        homelabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        contactpanel2 = new javax.swing.JPanel();
        homelabel8 = new javax.swing.JLabel();
        contactpanel3 = new javax.swing.JPanel();
        homelabel9 = new javax.swing.JLabel();
        contactpanel6 = new javax.swing.JPanel();
        homelabel12 = new javax.swing.JLabel();
        contactpanel7 = new javax.swing.JPanel();
        homelabel13 = new javax.swing.JLabel();
        contactpanel8 = new javax.swing.JPanel();
        homelabel14 = new javax.swing.JLabel();
        contactpanel9 = new javax.swing.JPanel();
        homelabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_receiptno = new javax.swing.JLabel();
        txt_paymentmode = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        txt_received = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_cheque = new javax.swing.JLabel();
        txt_cheque = new javax.swing.JLabel();
        lbl_bankname = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_bankname = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_year1 = new javax.swing.JLabel();
        txt_year2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_gst1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txt_roll = new javax.swing.JLabel();
        txt_coursename = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_coursenaam = new javax.swing.JLabel();
        txt_sgst = new javax.swing.JLabel();
        txt_coursename3 = new javax.swing.JLabel();
        txt_totalinwords = new javax.swing.JLabel();
        txt_cgst = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txt_initialamount1 = new javax.swing.JLabel();
        txt_totalamount = new javax.swing.JLabel();
        txt_remarks = new javax.swing.JLabel();
        txt_totalamount1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txt_initialamount4 = new javax.swing.JLabel();
        txt_initialamount5 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsidebar.setBackground(new java.awt.Color(51, 0, 153));
        panelsidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewrecordpanel.setBackground(new java.awt.Color(51, 0, 153));
        viewrecordpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        viewrecordpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewrecordpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewrecordpanelMouseExited(evt);
            }
        });
        viewrecordpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel.setForeground(new java.awt.Color(255, 255, 255));
        homelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/view all record.png"))); // NOI18N
        homelabel.setText("View Records");
        homelabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homelabelMouseClicked(evt);
            }
        });
        viewrecordpanel.add(homelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 300, 70));

        panelsidebar.add(viewrecordpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 330, 70));

        searchpanel.setBackground(new java.awt.Color(51, 0, 153));
        searchpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        searchpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchpanelMouseExited(evt);
            }
        });
        searchpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel1.setForeground(new java.awt.Color(255, 255, 255));
        homelabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/search2.png"))); // NOI18N
        homelabel1.setText("Search Record");
        homelabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homelabel1MouseClicked(evt);
            }
        });
        searchpanel.add(homelabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, -1));

        panelsidebar.add(searchpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 330, 70));

        editcoursepanel.setBackground(new java.awt.Color(51, 0, 153));
        editcoursepanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        editcoursepanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editcoursepanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editcoursepanelMouseExited(evt);
            }
        });
        editcoursepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel2.setForeground(new java.awt.Color(255, 255, 255));
        homelabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/edit2.png"))); // NOI18N
        homelabel2.setText("Edit Courses");
        homelabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homelabel2MouseClicked(evt);
            }
        });
        editcoursepanel.add(homelabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 60));

        panelsidebar.add(editcoursepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 330, 70));

        homepanel.setBackground(new java.awt.Color(51, 0, 153));
        homepanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        homepanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homepanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homepanelMouseExited(evt);
            }
        });
        homepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel3.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel3.setForeground(new java.awt.Color(255, 255, 255));
        homelabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/home.png"))); // NOI18N
        homelabel3.setText("  Home");
        homelabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homelabel3MouseClicked(evt);
            }
        });
        homepanel.add(homelabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 290, 50));

        panelsidebar.add(homepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 330, 70));

        backpanel.setBackground(new java.awt.Color(51, 0, 153));
        backpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        backpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backpanelMouseExited(evt);
            }
        });
        backpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel4.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel4.setForeground(new java.awt.Color(255, 255, 255));
        homelabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/back-button.png"))); // NOI18N
        homelabel4.setText("Back");
        homelabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homelabel4MouseClicked(evt);
            }
        });
        backpanel.add(homelabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 70));

        panelsidebar.add(backpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 330, 70));

        logoutpanel.setBackground(new java.awt.Color(51, 0, 153));
        logoutpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        logoutpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutpanelMouseExited(evt);
            }
        });
        logoutpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel5.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel5.setForeground(new java.awt.Color(255, 255, 255));
        homelabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/logout.png"))); // NOI18N
        homelabel5.setText("Logout");
        homelabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homelabel5MouseClicked(evt);
            }
        });
        logoutpanel.add(homelabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 70));

        panelsidebar.add(logoutpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 330, 70));

        contactpanel.setBackground(new java.awt.Color(51, 0, 153));
        contactpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        contactpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contactpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactpanelMouseExited(evt);
            }
        });
        contactpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel6.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel6.setForeground(new java.awt.Color(255, 255, 255));
        homelabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/admin.png"))); // NOI18N
        homelabel6.setText("Contact Us");
        homelabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homelabel6MouseClicked(evt);
            }
        });
        contactpanel.add(homelabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 280, 70));

        contactpanel1.setBackground(new java.awt.Color(51, 0, 153));
        contactpanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        contactpanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactpanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contactpanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactpanel1MouseExited(evt);
            }
        });
        contactpanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel7.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel7.setForeground(new java.awt.Color(255, 255, 255));
        homelabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/admin.png"))); // NOI18N
        homelabel7.setText("Contact Us");
        contactpanel1.add(homelabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 250, 70));

        contactpanel.add(contactpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, 330, 70));

        contactpanel4.setBackground(new java.awt.Color(51, 0, 153));
        contactpanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        contactpanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactpanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contactpanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactpanel4MouseExited(evt);
            }
        });
        contactpanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel10.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel10.setForeground(new java.awt.Color(255, 255, 255));
        homelabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/admin.png"))); // NOI18N
        homelabel10.setText("Contact Us");
        contactpanel4.add(homelabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 250, 70));

        contactpanel5.setBackground(new java.awt.Color(51, 0, 153));
        contactpanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        contactpanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactpanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contactpanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactpanel5MouseExited(evt);
            }
        });
        contactpanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel11.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel11.setForeground(new java.awt.Color(255, 255, 255));
        homelabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/admin.png"))); // NOI18N
        homelabel11.setText("Contact Us");
        contactpanel5.add(homelabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 250, 70));

        contactpanel4.add(contactpanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, 330, 70));

        contactpanel.add(contactpanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 710, 330, 70));

        panelsidebar.add(contactpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 330, 70));

        jLabel16.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 0, 153));
        jLabel16.setText("Remarks : ");
        panelsidebar.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 670, -1, 40));

        contactpanel2.setBackground(new java.awt.Color(51, 0, 153));
        contactpanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        contactpanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactpanel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contactpanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactpanel2MouseExited(evt);
            }
        });
        contactpanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel8.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel8.setForeground(new java.awt.Color(255, 255, 255));
        homelabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/edit2.png"))); // NOI18N
        homelabel8.setText("Edit");
        homelabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homelabel8MouseClicked(evt);
            }
        });
        contactpanel2.add(homelabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 290, 70));

        contactpanel3.setBackground(new java.awt.Color(51, 0, 153));
        contactpanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        contactpanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactpanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contactpanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactpanel3MouseExited(evt);
            }
        });
        contactpanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel9.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel9.setForeground(new java.awt.Color(255, 255, 255));
        homelabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/admin.png"))); // NOI18N
        homelabel9.setText("Contact Us");
        contactpanel3.add(homelabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 250, 70));

        contactpanel2.add(contactpanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, 330, 70));

        panelsidebar.add(contactpanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 700, 330, 70));

        contactpanel6.setBackground(new java.awt.Color(51, 0, 153));
        contactpanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        contactpanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactpanel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contactpanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactpanel6MouseExited(evt);
            }
        });
        contactpanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel12.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel12.setForeground(new java.awt.Color(255, 255, 255));
        homelabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/printer-.png"))); // NOI18N
        homelabel12.setText("     Print");
        homelabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homelabel12MouseClicked(evt);
            }
        });
        contactpanel6.add(homelabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 280, 70));

        contactpanel7.setBackground(new java.awt.Color(51, 0, 153));
        contactpanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        contactpanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactpanel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contactpanel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactpanel7MouseExited(evt);
            }
        });
        contactpanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel13.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel13.setForeground(new java.awt.Color(255, 255, 255));
        homelabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/admin.png"))); // NOI18N
        homelabel13.setText("Contact Us");
        contactpanel7.add(homelabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 250, 70));

        contactpanel6.add(contactpanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, 330, 70));

        contactpanel8.setBackground(new java.awt.Color(51, 0, 153));
        contactpanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        contactpanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactpanel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contactpanel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactpanel8MouseExited(evt);
            }
        });
        contactpanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel14.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel14.setForeground(new java.awt.Color(255, 255, 255));
        homelabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/admin.png"))); // NOI18N
        homelabel14.setText("Contact Us");
        contactpanel8.add(homelabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 250, 70));

        contactpanel9.setBackground(new java.awt.Color(51, 0, 153));
        contactpanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        contactpanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactpanel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contactpanel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactpanel9MouseExited(evt);
            }
        });
        contactpanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel15.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel15.setForeground(new java.awt.Color(255, 255, 255));
        homelabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/admin.png"))); // NOI18N
        homelabel15.setText("Contact Us");
        contactpanel9.add(homelabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 250, 70));

        contactpanel8.add(contactpanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, 330, 70));

        contactpanel6.add(contactpanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 710, 330, 70));

        panelsidebar.add(contactpanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 330, 70));

        getContentPane().add(panelsidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 1090));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/full-logo.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 170));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Chandigarh Educational Society Kharar, Village Jhanjeri, Sas Nagar Mohali, India 140301 India");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 830, 40));

        jPanel2.setBackground(new java.awt.Color(51, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 1190, 10));

        txt_receiptno.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txt_receiptno.setForeground(new java.awt.Color(255, 0, 51));
        txt_receiptno.setText("receiptno.");
        jPanel1.add(txt_receiptno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, 30));

        txt_paymentmode.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txt_paymentmode.setForeground(new java.awt.Color(255, 0, 51));
        txt_paymentmode.setText("paymentmode");
        jPanel1.add(txt_paymentmode, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, 30));

        txt_date.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txt_date.setForeground(new java.awt.Color(255, 0, 51));
        txt_date.setText("date");
        jPanel1.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, -1, 30));

        txt_received.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txt_received.setForeground(new java.awt.Color(255, 0, 51));
        txt_received.setText("received");
        jPanel1.add(txt_received, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, -1, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 153));
        jLabel12.setText("Payment Mode -");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 30));

        lbl_cheque.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lbl_cheque.setForeground(new java.awt.Color(51, 0, 153));
        lbl_cheque.setText("Cheque_DD - ");
        jPanel1.add(lbl_cheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, 30));

        txt_cheque.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txt_cheque.setForeground(new java.awt.Color(255, 0, 51));
        txt_cheque.setText("Cheque_DD  ");
        jPanel1.add(txt_cheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, 30));

        lbl_bankname.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lbl_bankname.setForeground(new java.awt.Color(51, 0, 153));
        lbl_bankname.setText("Bank Name :   ");
        jPanel1.add(lbl_bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 0, 153));
        jLabel17.setText("The following payment in the collge 0ffice for the year");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 30));

        txt_bankname.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txt_bankname.setForeground(new java.awt.Color(255, 0, 51));
        txt_bankname.setText("bankname  ");
        jPanel1.add(txt_bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 0, 153));
        jLabel19.setText("-");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 0, 153));
        jLabel20.setText("Account(s)");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, -1, 30));

        txt_year1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txt_year1.setForeground(new java.awt.Color(255, 0, 51));
        txt_year1.setText("2021");
        jPanel1.add(txt_year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, 30));

        txt_year2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txt_year2.setForeground(new java.awt.Color(255, 0, 51));
        txt_year2.setText("2022");
        jPanel1.add(txt_year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 40, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 153));
        jLabel11.setText("Receipt No. :   CEC- ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 0, 153));
        jLabel18.setText("Date");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, -1, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 0, 153));
        jLabel21.setText("GstIN : ");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, -1, 30));

        txt_gst1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txt_gst1.setForeground(new java.awt.Color(51, 51, 51));
        txt_gst1.setText("GstIN : ");
        jPanel1.add(txt_gst1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, -1, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 1270, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 590, 380, 20));

        txt_roll.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txt_roll.setForeground(new java.awt.Color(255, 0, 51));
        txt_roll.setText("RollNo. :");
        jPanel1.add(txt_roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, -1, 30));

        txt_coursename.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txt_coursename.setForeground(new java.awt.Color(51, 0, 153));
        txt_coursename.setText("sgst 9%");
        jPanel1.add(txt_coursename, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 180, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 0, 153));
        jLabel24.setText("Head");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, -1, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 0, 153));
        jLabel25.setText("SR No");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 50, 30));

        jLabel26.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 0, 153));
        jLabel26.setText("1");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 20, 30));

        txt_coursenaam.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txt_coursenaam.setForeground(new java.awt.Color(51, 0, 153));
        txt_coursenaam.setText("course_name");
        jPanel1.add(txt_coursenaam, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 180, 30));

        txt_sgst.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txt_sgst.setForeground(new java.awt.Color(255, 0, 51));
        txt_sgst.setText("sgst");
        jPanel1.add(txt_sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, 180, 30));

        txt_coursename3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txt_coursename3.setForeground(new java.awt.Color(51, 0, 153));
        txt_coursename3.setText("cgst 9%");
        jPanel1.add(txt_coursename3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 180, 30));

        txt_totalinwords.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txt_totalinwords.setForeground(new java.awt.Color(255, 0, 51));
        txt_totalinwords.setText("Total in words : ");
        jPanel1.add(txt_totalinwords, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 650, 280, 30));

        txt_cgst.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txt_cgst.setForeground(new java.awt.Color(255, 0, 51));
        txt_cgst.setText("cgst");
        jPanel1.add(txt_cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 180, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 1210, 20));

        txt_initialamount1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txt_initialamount1.setForeground(new java.awt.Color(255, 0, 51));
        txt_initialamount1.setText("Initial_amount ");
        jPanel1.add(txt_initialamount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 180, 30));

        txt_totalamount.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txt_totalamount.setForeground(new java.awt.Color(51, 0, 153));
        txt_totalamount.setText("Total Amount");
        jPanel1.add(txt_totalamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, 180, 30));

        txt_remarks.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txt_remarks.setText("Remarks :");
        jPanel1.add(txt_remarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 730, 780, 30));

        txt_totalamount1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txt_totalamount1.setForeground(new java.awt.Color(51, 0, 255));
        txt_totalamount1.setText("Receiver's Signature");
        jPanel1.add(txt_totalamount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 690, 180, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 680, 310, 10));

        txt_initialamount4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txt_initialamount4.setForeground(new java.awt.Color(51, 0, 153));
        txt_initialamount4.setText("Total in words : ");
        jPanel1.add(txt_initialamount4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 110, 30));

        txt_initialamount5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txt_initialamount5.setForeground(new java.awt.Color(51, 0, 153));
        txt_initialamount5.setText("Remarks :");
        jPanel1.add(txt_initialamount5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, 110, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 0, 153));
        jLabel23.setText("Received From :");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, 30));

        jLabel27.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 0, 153));
        jLabel27.setText("RollNo. :");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 1220, 860));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void viewrecordpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewrecordpanelMouseEntered
        Color clr = new Color(48,0,178);
        viewrecordpanel.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_viewrecordpanelMouseEntered

    private void viewrecordpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewrecordpanelMouseExited
        Color clr = new Color(51,0,153);
        viewrecordpanel.setBackground(clr);
    }//GEN-LAST:event_viewrecordpanelMouseExited

    private void searchpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchpanelMouseEntered
        Color clr = new Color(48,0,178);
        searchpanel.setBackground(clr);
    }//GEN-LAST:event_searchpanelMouseEntered

    private void searchpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchpanelMouseExited
        Color clr = new Color(51,0,153);
        searchpanel.setBackground(clr);
    }//GEN-LAST:event_searchpanelMouseExited

    private void editcoursepanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editcoursepanelMouseEntered
        Color clr = new Color(48,0,178);
        editcoursepanel.setBackground(clr);
    }//GEN-LAST:event_editcoursepanelMouseEntered

    private void editcoursepanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editcoursepanelMouseExited
        Color clr = new Color(51,0,153);
        editcoursepanel.setBackground(clr);
    }//GEN-LAST:event_editcoursepanelMouseExited

    private void homepanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepanelMouseEntered
        Color clr = new Color(48,0,178);
        homepanel.setBackground(clr);
    }//GEN-LAST:event_homepanelMouseEntered

    private void homepanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepanelMouseExited
        Color clr = new Color(51,0,153);
        homepanel.setBackground(clr);
    }//GEN-LAST:event_homepanelMouseExited

    private void backpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backpanelMouseEntered
        Color clr = new Color(48,0,178);
        backpanel.setBackground(clr);
    }//GEN-LAST:event_backpanelMouseEntered

    private void backpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backpanelMouseExited
        Color clr = new Color(51,0,153);
        backpanel.setBackground(clr);
    }//GEN-LAST:event_backpanelMouseExited

    private void homelabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelabel5MouseClicked
         LoginPage lp = new LoginPage();
       lp.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_homelabel5MouseClicked

    private void logoutpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutpanelMouseClicked
        SignuUpPage signup = new SignuUpPage();
        signup.show();
        this.dispose();
    }//GEN-LAST:event_logoutpanelMouseClicked

    private void logoutpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutpanelMouseEntered
        Color clr = new Color(48,0,178);
        logoutpanel.setBackground(clr);
    }//GEN-LAST:event_logoutpanelMouseEntered

    private void logoutpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutpanelMouseExited
        Color clr = new Color(51,0,153);
        logoutpanel.setBackground(clr);
    }//GEN-LAST:event_logoutpanelMouseExited

    private void contactpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanelMouseClicked
        ContactUs contact = new ContactUs();
        contact.show();
    }//GEN-LAST:event_contactpanelMouseClicked

    private void contactpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanelMouseEntered
        Color clr = new Color(48,0,178);
        contactpanel.setBackground(clr);
    }//GEN-LAST:event_contactpanelMouseEntered

    private void contactpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanelMouseExited
        Color clr = new Color(51,0,153);
        contactpanel.setBackground(clr);
    }//GEN-LAST:event_contactpanelMouseExited

    private void contactpanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel1MouseClicked

    private void contactpanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel1MouseEntered

    private void contactpanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel1MouseExited

    private void contactpanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel3MouseClicked

    private void contactpanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel3MouseEntered

    private void contactpanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel3MouseExited

    private void contactpanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel2MouseClicked

    private void contactpanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel2MouseEntered

    private void contactpanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel2MouseExited

    private void contactpanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel5MouseClicked

    private void contactpanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel5MouseEntered

    private void contactpanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel5MouseExited

    private void contactpanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel4MouseClicked

    private void contactpanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel4MouseEntered

    private void contactpanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel4MouseExited

    private void contactpanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel7MouseClicked

    private void contactpanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel7MouseEntered

    private void contactpanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel7MouseExited

    private void contactpanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel9MouseClicked

    private void contactpanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel9MouseEntered

    private void contactpanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel9MouseExited

    private void contactpanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel8MouseClicked

    private void contactpanel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel8MouseEntered

    private void contactpanel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel8MouseExited

    private void contactpanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel6MouseClicked

    private void contactpanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel6MouseEntered

    private void contactpanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanel6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_contactpanel6MouseExited

    private void homelabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelabel12MouseClicked
        PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
                jPanel1.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }
    }//GEN-LAST:event_homelabel12MouseClicked

    private void homelabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelabel8MouseClicked
       UpdateAddFees up = new UpdateAddFees();
       up.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_homelabel8MouseClicked

    private void homelabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelabel6MouseClicked
ContactUs cs = new   ContactUs();
cs.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_homelabel6MouseClicked

    private void homelabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelabel3MouseClicked
 HomePage hm =new HomePage();
       hm.setVisible(true);
       this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_homelabel3MouseClicked

    private void homelabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelabel1MouseClicked
 SearchRecords sr = new SearchRecords();
      sr.setVisible(true);
      this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_homelabel1MouseClicked

    private void homelabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelabelMouseClicked
viewAllRecords vi = new  viewAllRecords();
vi.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_homelabelMouseClicked

    private void homelabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelabel4MouseClicked
 HomePage hm =new HomePage();
       hm.setVisible(true);
       this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_homelabel4MouseClicked

    private void homelabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelabel2MouseClicked
EditCourse ec = new   EditCourse();
ec.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_homelabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backpanel;
    private javax.swing.JPanel contactpanel;
    private javax.swing.JPanel contactpanel1;
    private javax.swing.JPanel contactpanel2;
    private javax.swing.JPanel contactpanel3;
    private javax.swing.JPanel contactpanel4;
    private javax.swing.JPanel contactpanel5;
    private javax.swing.JPanel contactpanel6;
    private javax.swing.JPanel contactpanel7;
    private javax.swing.JPanel contactpanel8;
    private javax.swing.JPanel contactpanel9;
    private javax.swing.JPanel editcoursepanel;
    private javax.swing.JLabel homelabel;
    private javax.swing.JLabel homelabel1;
    private javax.swing.JLabel homelabel10;
    private javax.swing.JLabel homelabel11;
    private javax.swing.JLabel homelabel12;
    private javax.swing.JLabel homelabel13;
    private javax.swing.JLabel homelabel14;
    private javax.swing.JLabel homelabel15;
    private javax.swing.JLabel homelabel2;
    private javax.swing.JLabel homelabel3;
    private javax.swing.JLabel homelabel4;
    private javax.swing.JLabel homelabel5;
    private javax.swing.JLabel homelabel6;
    private javax.swing.JLabel homelabel7;
    private javax.swing.JLabel homelabel8;
    private javax.swing.JLabel homelabel9;
    private javax.swing.JPanel homepanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbl_bankname;
    private javax.swing.JLabel lbl_cheque;
    private javax.swing.JPanel logoutpanel;
    private javax.swing.JPanel panelsidebar;
    private javax.swing.JPanel searchpanel;
    private javax.swing.JLabel txt_bankname;
    private javax.swing.JLabel txt_cgst;
    private javax.swing.JLabel txt_cheque;
    private javax.swing.JLabel txt_coursenaam;
    private javax.swing.JLabel txt_coursename;
    private javax.swing.JLabel txt_coursename3;
    private javax.swing.JLabel txt_date;
    private javax.swing.JLabel txt_gst1;
    private javax.swing.JLabel txt_initialamount1;
    private javax.swing.JLabel txt_initialamount4;
    private javax.swing.JLabel txt_initialamount5;
    private javax.swing.JLabel txt_paymentmode;
    private javax.swing.JLabel txt_receiptno;
    private javax.swing.JLabel txt_received;
    private javax.swing.JLabel txt_remarks;
    private javax.swing.JLabel txt_roll;
    private javax.swing.JLabel txt_sgst;
    private javax.swing.JLabel txt_totalamount;
    private javax.swing.JLabel txt_totalamount1;
    private javax.swing.JLabel txt_totalinwords;
    private javax.swing.JLabel txt_year1;
    private javax.swing.JLabel txt_year2;
    private javax.swing.JPanel viewrecordpanel;
    // End of variables declaration//GEN-END:variables
}
