/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication7;

import java.awt.Color;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author CHIRAG VOHRA
 */
 
public class viewAllRecords extends javax.swing.JFrame {

    /**
     * Creates new form SearchRecords
     */
    DefaultTableModel model;
    public viewAllRecords() {
        initComponents();
        setRecordstoTable();
    }
public void setRecordstoTable(){
            try{
               Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/fees_mange_sys","root","Chirag@123");
            PreparedStatement pst = con.prepareStatement("select * from feess");
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                String receiptNo = rs.getString("receiptno");
                String rollnumber = rs.getString("rolllnoo");
                String studentname=rs.getString("studentnaam");
                String course=rs.getString("coursenaam");
                String payment=rs.getString("paymentMode");
                float amountt = rs.getFloat("totalMoney");
                String remark=rs.getString("remarkss");
                
                Object[] obj = {receiptNo,rollnumber,studentname,course,payment,amountt,remark};
               model = (DefaultTableModel)tbl_records.getModel();
               model.addRow(obj);
            }
            }catch(Exception e){
                e.printStackTrace();
            }
        }
public void search(String str){
    model = (DefaultTableModel)tbl_records.getModel();
    TableRowSorter<DefaultTableModel> trs = new TableRowSorter<DefaultTableModel>(model);
    tbl_records.setRowSorter(trs);
    trs.setRowFilter(RowFilter.regexFilter(str));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsidebar = new javax.swing.JPanel();
        viewrecordpanel = new javax.swing.JPanel();
        homelabel = new javax.swing.JLabel();
        searchpanel = new javax.swing.JPanel();
        homelabel1 = new javax.swing.JLabel();
        editcoursepanel = new javax.swing.JPanel();
        homelabel2 = new javax.swing.JLabel();
        homepanel = new javax.swing.JPanel();
        homelabel3 = new javax.swing.JLabel();
        backpanel = new javax.swing.JPanel();
        homelabel4 = new javax.swing.JLabel();
        logoutpanel = new javax.swing.JPanel();
        homelabel5 = new javax.swing.JLabel();
        contactpanel = new javax.swing.JPanel();
        homelabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_records = new javax.swing.JTable();
        homelabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsidebar.setBackground(new java.awt.Color(51, 0, 153));
        panelsidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewrecordpanel.setBackground(new java.awt.Color(51, 0, 153));
        viewrecordpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        viewrecordpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewrecordpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewrecordpanelMouseExited(evt);
            }
        });
        viewrecordpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel.setForeground(new java.awt.Color(255, 255, 255));
        homelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/view all record.png"))); // NOI18N
        homelabel.setText("View Records");
        homelabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homelabelMouseClicked(evt);
            }
        });
        viewrecordpanel.add(homelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 300, 70));

        panelsidebar.add(viewrecordpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 330, 70));

        searchpanel.setBackground(new java.awt.Color(51, 0, 153));
        searchpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        searchpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchpanelMouseExited(evt);
            }
        });
        searchpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel1.setForeground(new java.awt.Color(255, 255, 255));
        homelabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/search2.png"))); // NOI18N
        homelabel1.setText("Search Record");
        homelabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homelabel1MouseClicked(evt);
            }
        });
        searchpanel.add(homelabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 290, -1));

        panelsidebar.add(searchpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 330, 70));

        editcoursepanel.setBackground(new java.awt.Color(51, 0, 153));
        editcoursepanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        editcoursepanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editcoursepanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editcoursepanelMouseExited(evt);
            }
        });
        editcoursepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel2.setForeground(new java.awt.Color(255, 255, 255));
        homelabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/edit2.png"))); // NOI18N
        homelabel2.setText("Edit Courses");
        homelabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homelabel2MouseClicked(evt);
            }
        });
        editcoursepanel.add(homelabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 290, 60));

        panelsidebar.add(editcoursepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 330, 70));

        homepanel.setBackground(new java.awt.Color(51, 0, 153));
        homepanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        homepanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homepanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homepanelMouseExited(evt);
            }
        });
        homepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel3.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel3.setForeground(new java.awt.Color(255, 255, 255));
        homelabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/home.png"))); // NOI18N
        homelabel3.setText("  Home");
        homelabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homelabel3MouseClicked(evt);
            }
        });
        homepanel.add(homelabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 290, 50));

        panelsidebar.add(homepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 330, 70));

        backpanel.setBackground(new java.awt.Color(51, 0, 153));
        backpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        backpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backpanelMouseExited(evt);
            }
        });
        backpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel4.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel4.setForeground(new java.awt.Color(255, 255, 255));
        homelabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/back-button.png"))); // NOI18N
        homelabel4.setText("Back");
        homelabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homelabel4MouseClicked(evt);
            }
        });
        backpanel.add(homelabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 70));

        panelsidebar.add(backpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 330, 70));

        logoutpanel.setBackground(new java.awt.Color(51, 0, 153));
        logoutpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        logoutpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutpanelMouseExited(evt);
            }
        });
        logoutpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel5.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel5.setForeground(new java.awt.Color(255, 255, 255));
        homelabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/logout.png"))); // NOI18N
        homelabel5.setText("Logout");
        homelabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homelabel5MouseClicked(evt);
            }
        });
        logoutpanel.add(homelabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 70));

        panelsidebar.add(logoutpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 330, 70));

        contactpanel.setBackground(new java.awt.Color(51, 0, 153));
        contactpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        contactpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contactpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactpanelMouseExited(evt);
            }
        });
        contactpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homelabel6.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel6.setForeground(new java.awt.Color(255, 255, 255));
        homelabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/admin.png"))); // NOI18N
        homelabel6.setText("Contact Us");
        contactpanel.add(homelabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 250, 70));

        panelsidebar.add(contactpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 330, 70));

        jLabel16.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 0, 153));
        jLabel16.setText("Remarks : ");
        panelsidebar.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 670, -1, 40));

        getContentPane().add(panelsidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 1040));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_records.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Receipt No.", "Roll No.", "Student Name", "Course ", "Payment Mode", "Amount", "Remarks"
            }
        ));
        jScrollPane1.setViewportView(tbl_records);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 1070, 710));

        homelabel7.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        homelabel7.setForeground(new java.awt.Color(0, 51, 51));
        homelabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/images/view all record.png"))); // NOI18N
        homelabel7.setText("View Records");
        jPanel1.add(homelabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 290, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("What I can Search for you :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 230, 30));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 92, 230, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 1130, 1030));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewrecordpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewrecordpanelMouseEntered
        Color clr = new Color(48,0,178);
        viewrecordpanel.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_viewrecordpanelMouseEntered

    private void viewrecordpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewrecordpanelMouseExited
        Color clr = new Color(51,0,153);
        viewrecordpanel.setBackground(clr);
    }//GEN-LAST:event_viewrecordpanelMouseExited

    private void searchpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchpanelMouseEntered
        Color clr = new Color(48,0,178);
        searchpanel.setBackground(clr);
    }//GEN-LAST:event_searchpanelMouseEntered

    private void searchpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchpanelMouseExited
        Color clr = new Color(51,0,153);
        searchpanel.setBackground(clr);
    }//GEN-LAST:event_searchpanelMouseExited

    private void editcoursepanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editcoursepanelMouseEntered
        Color clr = new Color(48,0,178);
        editcoursepanel.setBackground(clr);
    }//GEN-LAST:event_editcoursepanelMouseEntered

    private void editcoursepanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editcoursepanelMouseExited
        Color clr = new Color(51,0,153);
        editcoursepanel.setBackground(clr);
    }//GEN-LAST:event_editcoursepanelMouseExited

    private void homepanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepanelMouseEntered
        Color clr = new Color(48,0,178);
        homepanel.setBackground(clr);
    }//GEN-LAST:event_homepanelMouseEntered

    private void homepanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepanelMouseExited
        Color clr = new Color(51,0,153);
        homepanel.setBackground(clr);
    }//GEN-LAST:event_homepanelMouseExited

    private void backpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backpanelMouseEntered
        Color clr = new Color(48,0,178);
        backpanel.setBackground(clr);
    }//GEN-LAST:event_backpanelMouseEntered

    private void backpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backpanelMouseExited
        Color clr = new Color(51,0,153);
        backpanel.setBackground(clr);
    }//GEN-LAST:event_backpanelMouseExited

    private void homelabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelabel5MouseClicked
         LoginPage lp = new LoginPage();
       lp.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_homelabel5MouseClicked

    private void logoutpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutpanelMouseClicked
        SignuUpPage signup = new SignuUpPage();
        signup.show();
        this.dispose();
    }//GEN-LAST:event_logoutpanelMouseClicked

    private void logoutpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutpanelMouseEntered
        Color clr = new Color(48,0,178);
        logoutpanel.setBackground(clr);
    }//GEN-LAST:event_logoutpanelMouseEntered

    private void logoutpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutpanelMouseExited
        Color clr = new Color(51,0,153);
        logoutpanel.setBackground(clr);
    }//GEN-LAST:event_logoutpanelMouseExited

    private void contactpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanelMouseClicked
        ContactUs contact = new ContactUs();
        contact.show();
    }//GEN-LAST:event_contactpanelMouseClicked

    private void contactpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanelMouseEntered
        Color clr = new Color(48,0,178);
        contactpanel.setBackground(clr);
    }//GEN-LAST:event_contactpanelMouseEntered

    private void contactpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactpanelMouseExited
        Color clr = new Color(51,0,153);
        contactpanel.setBackground(clr);
    }//GEN-LAST:event_contactpanelMouseExited

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
       String searchString = jTextField1.getText();
       search(searchString);
    }//GEN-LAST:event_jTextField1KeyReleased

    private void homelabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelabel3MouseClicked
 HomePage hm =new HomePage();
       hm.setVisible(true);
       this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_homelabel3MouseClicked

    private void homelabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelabel1MouseClicked
 SearchRecords sr = new SearchRecords();
      sr.setVisible(true);
      this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_homelabel1MouseClicked

    private void homelabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelabelMouseClicked
viewAllRecords vi = new  viewAllRecords();
vi.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_homelabelMouseClicked

    private void homelabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelabel4MouseClicked
 HomePage hm =new HomePage();
       hm.setVisible(true);
       this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_homelabel4MouseClicked

    private void homelabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelabel2MouseClicked
EditCourse ec = new   EditCourse();
ec.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_homelabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewAllRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backpanel;
    private javax.swing.JPanel contactpanel;
    private javax.swing.JPanel editcoursepanel;
    private javax.swing.JLabel homelabel;
    private javax.swing.JLabel homelabel1;
    private javax.swing.JLabel homelabel2;
    private javax.swing.JLabel homelabel3;
    private javax.swing.JLabel homelabel4;
    private javax.swing.JLabel homelabel5;
    private javax.swing.JLabel homelabel6;
    private javax.swing.JLabel homelabel7;
    private javax.swing.JPanel homepanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel logoutpanel;
    private javax.swing.JPanel panelsidebar;
    private javax.swing.JPanel searchpanel;
    private javax.swing.JTable tbl_records;
    private javax.swing.JPanel viewrecordpanel;
    // End of variables declaration//GEN-END:variables
}
